const constants = {
  API_URL: "http://localhost:5000/api/v1",
  profilePlaceholder:
    "https://st3.depositphotos.com/6672868/13701/v/450/depositphotos_137014128-stock-illustration-user-profile-icon.jpg",

  imagePlaceholder:
    "https://png.pngtree.com/png-vector/20190223/ourmid/pngtree-vector-picture-icon-png-image_695350.jpg",

  //RECIPE TAGS
  TAGS: [
    "#RecipeIdeas",
    "#EasyRecipes",
    "#DeliciousDishes",
    "#HomeCooking",
    "#HealthyEats",
    "#InstaRecipe",
    "#CookingTips",
    "#RecipeShare",
    "#TastyTreats",
    "#FamilyFavorites",
    "#DinnerInspiration",
    "#QuickMeals",
    "#FoodPhotography",
    "#BakingAdventures",
    "#OnePotWonders",
    "#MealPrepIdeas",
    "#VeggieDelights",
    "#GlutenFreeEats",
    "#DessertHeaven",
    "#BrunchRecipes",
    "#BudgetFriendly",
    "#FlavorfulDishes",
    "#CookbookInspiration",
    "#InternationalCuisine",
    "#ComfortFood",
    "#AppetizerLove",
    "#NutritiousNoms",
    "#FoodieFinds",
    "#WeeknightWinners",
    "#SlowCookerMagic",
  ],

  //RECIPE CATEGORIES
  CATEGORIES: {
    Cuisines: [
      "Ethiopian",
      "Italian",
      "Mexican",
      "Chinese",
      "Indian",
      "Thai",
      "French",
      "Japanese",
    ],
    "Dish Type": [
      "Appetizers",
      "Main Courses",
      "Desserts",
      "Salads",
      "Soups",
      "Sandwiches",
      "Breakfast/Brunch",
      "Beverages",
      "Snacks",
    ],
    "Dietary Preferences": [
      "Vegetarian",
      "Vegan",
      "Gluten-free",
      "Dairy-free",
      "Low-carb",
      "Nut-free",
      "Sugar-free",
      "Pescatarian",
      "Plant-based",
      "Low-sodium",
    ],
    "Meal Course": [
      "Weeknight Dinners",
      "One-Pot Meals",
      "Quick and Easy",
      "Budget-friendly",
      "Family Favorites",
      "Special Occasions",
      "Picnic Ideas",
      "Comfort Food",
      "High-Protein",
      "Low-Calorie",
      "Date Night",
      "Kids' Favorites",
    ],
  },
};

export default constants;
